GET http://localhost:3000/todos

###
POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text": "buy bread 🍞 "
}

###
DELETE http://localhost:3000/todo/delete/63b8945a92f5a657841f20e1

###
GET http://localhost:3000/todo/complete/63b73703a6adf32872c9aa8d