GET http://localhost:3000/todos

###
POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text": "get bread 🍞 "
}

###
DELETE http://localhost:3000/todo/delete/63b31b0069024857d1c4671b

###
PUT http://localhost:3000/todo/complete/63b31b0069024857d1c4671d